### ISSUE TITLE
Sorry - Gateway timeout again

### ISSUE THREAD

**Issue by kz6fittycent** [robvanbakel/gotiny-api#3]
```
curl -X POST https://gotiny.cc/api -H "Content-Type: application/json" -d '{ "input" : "www.my-superlong-url-here.com" }'
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

Same as Issue #2

**Comment by kz6fittycent** [comment]
I've made 10 (successful) calls within a 4 hour period, just in case you're wondering.

**Comment by kz6fittycent** [comment]
Never mind - online again!

**Comment by kz6fittycent** [comment]
Sorry, I know this may be a bother but it seems to happen everyday for several hours, then it comes back online. 

edit:

I don't have exact times but it seems to range from `~15:00 UTC` to `~20:00 UTC`; perhaps even longer.

**Comment by robvanbakel** [comment]
Don't be bothered, I'm very grateful for your help! I'm not sure what caused the outages. Since it's happened a few times over the last couple of days, it might be some structural problem I'm not aware of. I'll keep a close eye on the logs while I try to pinpoint the root of the problem. 

I'll use this threat to report updates to the issue.

**Comment by kz6fittycent** [comment]
I wrote a script that logs the timestamp for when I actually run into the error. See below for the most recent issue. Again, this isn't going to be consistent, because it relies on my use of the API to actually see the error. Time is Chicago/Central Time.

`API_ERROR_2022-02-17-15:26:19`

**Comment by robvanbakel** [comment]
I've created a [logging system](https://github.com/robvanbakel/monitor/blob/main/src/gotiny/createShortLink.ts) as well, which has been running on a set interval. I did not come across any issues over the last week, but today there were two outages again.

Since GoTiny is self-hosted right now and those crashes are paired with spikes in CPU usage; I'll move to a cloud-based hosting over the weekend, to test if that improves stability. I'll keep the ticket updated!

**Comment by robvanbakel** [comment]
I think have might have found the issue causing the API to crash. In some cases, the regular expression used to check for valid URLs in a string would not return, causing the function to run infinitely, eventually crashing the server. Normally, either an array or `null` is returned from this function, but in these cases, neither would happen.

I [updated the regular expression](https://github.com/robvanbakel/gotiny-api/commit/b89273b72db6d1353e4b6c317745c9f7a1e3fc7d) and I haven't been able to make it crash yet. Strings that would cause problems with the old version just return as `null` instantly now, causing no problems whatsoever.

I'll keep on monitoring and testing in the coming week, but I'm feeling confident this was the bug that caused the outages.

**Comment by kz6fittycent** [comment]
Awesome! The last time there was an error was the one I posted yesterday.

**Comment by kz6fittycent** [comment]
I've not seen any issues since your fix. If you feel like this is worth closing, I'm thinking the same.

**Comment by robvanbakel** [comment]
Good to hear, I haven't encountered any strange behavior myself. I'll definitely keep the monitoring tool running and close the ticket for now. Thanks for your help and proactivity!
