### ISSUE TITLE
#Bug: Redirects loops.

### ISSUE THREAD

**Issue by ghost** [robvanbakel/gotiny-api#7]
## `#BUG` - Redirect loops

- Hello, I believe it is necessary to fix the vulnerability of redirects in excessive 
or "redirects loops".

```bash
# CREATE URL
curl -X POST https://gotiny.cc/api 
     -H  "Content-Type: application/json" 
     -d '{ "input" : "https://www.google.com/?q=Node.js" }'
     
# CREATE URL/OUTPUT
 -> gotiny.cc/{any_slug}
 
# CREATE URL WITH/LOOP
# In this case a new POST request is made with the URL already shortened causing the LOOP.
# The input provided is an already shortened URL.

curl -X POST https://gotiny.cc/api 
     -H  "Content-Type: application/json" 
     -d '{ "input" : "gotiny.cc/{any_slug}" }'
```

### Resolution (using TypeScript)

```typescript
const VULNERABLE_DOMAINS: string[] = ['gotiny.cc'] as const;

function isVulnerableDomain(href = 'https://gotiny.cc/x6pskx'): boolean {
  try {
    const url = new URL(href);

    if (VULNERABLE_DOMAINS.includes(url?.host)) {
      //throw new Error('Invalid domain or URL already SHORT');
      return true;
    } else {
      // Your implementation here...
      return true 
    }
  } catch(error: any) { return true }
}
 
isVulnerableDomain('any_domain_or_url') // -> false
isVulnerableDomain('https://gotiny.cc/{{any_slug}}') // -> true
```

**Comment by robvanbakel** [comment]
Thanks for your feedback! Being able to create redirect loops and long chains of short links have purposefully been part of GoTiny since the beginning. I wanted to create a lightweight API with as little restrictions as possible, to make working with it super ease. However, as you pointed out; some of these features can be used in ways that aren't ideal.

Coincidentally, I'm working on a larger update which fixes this issue, among other issues I've spotted as GoTiny has grown in popularity. Because of this, I'm closing https://github.com/robvanbakel/gotiny-api/pull/8 for now; I very much appreciate your help and suggestions, though!

**Comment by ghost** [comment]
Okay. I'm looking forward to the new version
